<a href="https://colab.research.google.com/github/sanvi1510/Pytorch/blob/main/Pytorch_lec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Creation

In [ ]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"Is CUDA available: {torch.cuda.is_available()}")


PyTorch version: 2.11.0+cpu
Is CUDA available: False


METHODS TO CREAT TENSORS:


1. **EMPTY** :JUST ASSIGN THE MEMORY AND NOT THE VALUES THERE ARE GARBAGE VALUES


In [ ]:
A=torch.empty(1,3,2)

A


tensor([[[1.5414e-43, 1.6115e-43],
         [1.5554e-43, 1.5975e-43],
         [5.6052e-44, 1.2752e-43]]])

In [ ]:
type(A)

torch.Tensor

2.**ZEROs** : all the values are intiallized to 0 (e.g nueral n/w weights intialization)

In [ ]:
B=torch.zeros(1,3,2)
B

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])

3.**RAND**: randoms values b/w 0 to 1  used to intailize


     Issue: each time random values not reproducible

     SEED:CODE TO MAKE REPRODUCIBLITY

In [ ]:
C=torch.rand(1,3,2)
C

tensor([[[0.6120, 0.9015],
         [0.7246, 0.2532],
         [0.7758, 0.8620]]])

4.**Torch.tensor: Coustom tensor**

In [ ]:
D=torch.tensor([[1,2,3],[3,2,1]])
D

tensor([[1, 2, 3],
        [3, 2, 1]])

5.Arange
6.linspace
7.identity matrix
8.full:all values intialized to the given

**SHAPE OF TENSORS**

In [ ]:
A.shape

torch.Size([1, 3, 2])

tensor of same shape as the other

In [ ]:
E=torch.empty_like(A)
E

tensor([[[6.8268e-18, 4.4847e-41],
         [2.2731e-21, 0.0000e+00],
         [4.4842e-44, 0.0000e+00]]])

In [ ]:
F=torch.zeros_like(A)
F

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
G=torch.ones_like(A)
G

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
H=torch.rand_like(A)
H

tensor([[[0.3699, 0.8329],
         [0.0823, 0.5038],
         [0.2171, 0.5681]]])

Data Types in tensor


In [ ]:
A.dtype
H.dtype

torch.float32

In [ ]:
I=torch.randint_like(A, low=0, high=10, dtype=torch.int32)
I

tensor([[[1, 6],
         [3, 5],
         [8, 3]]], dtype=torch.int32)

In [ ]:
I.to(torch.float32)

tensor([[[1., 6.],
         [3., 5.],
         [8., 3.]]])

**OPERATIONS ON TENSORS**

      1.SCALER OPS

In [ ]:
Y=A+1
Y

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
X=(A*100)//10
X

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
X=A**2
X

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])

     2.ELEMENT WISE OPS

In [ ]:
X=A+B
X

tensor([[[1.5414e-43, 1.6115e-43],
         [1.5554e-43, 1.5975e-43],
         [5.6052e-44, 1.2752e-43]]])

ABSOLUTE VALUE

In [ ]:
torch.abs(X)

tensor([[[1.5414e-43, 1.6115e-43],
         [1.5554e-43, 1.5975e-43],
         [5.6052e-44, 1.2752e-43]]])

In [ ]:
torch.neg(X)

tensor([[[-1.5414e-43, -1.6115e-43],
         [-1.5554e-43, -1.5975e-43],
         [-5.6052e-44, -1.2752e-43]]])

In [ ]:
torch.round(X)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
torch.ceil(X)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]]])

CLAMP:set a boundry for the value and  then apply the cap

In [ ]:
torch.clamp(C,min=0.5,max=0.7)

tensor([[[0.6120, 0.7000],
         [0.7000, 0.5000],
         [0.7000, 0.7000]]])

Reduction operations

  1.sum

In [ ]:
a=torch.sum(A)
a

tensor(8.1415e-43)

In [62]:
a1=torch.sum(A,dim=1)
a1

tensor([[3.6574e-43, 4.4842e-43]])

  2.Mean:only for float datatype

In [64]:
a2=torch.mean(A)
a2

tensor(1.3593e-43)

max_mean

Variance

Standard deviation

Arg_max :position of the max element


Arg_min

**MATRIX OPS**

transpose

Multipication:matmul

dot product

determinant

inverse

**COMPARISION OPS:B/W ALL THE CORRESPONDING ELEMENTS**

**ARITHEMATIC**

  Relu

softmax

**INPLACE OPS**

In [66]:
A.add_(B)

tensor([[[1.5414e-43, 1.6115e-43],
         [1.5554e-43, 1.5975e-43],
         [5.6052e-44, 1.2752e-43]]])

In [67]:
A

tensor([[[1.5414e-43, 1.6115e-43],
         [1.5554e-43, 1.5975e-43],
         [5.6052e-44, 1.2752e-43]]])

**COPYING TENSOR**

In [69]:
b=A
b

tensor([[[1.5414e-43, 1.6115e-43],
         [1.5554e-43, 1.5975e-43],
         [5.6052e-44, 1.2752e-43]]])

ISSUE:the changes in A are reflected in b as they are stored in the same memory location

In [70]:
id(A)

137455650037408

In [71]:
id(b)

137455650037408

SOLution

In [72]:
c=A.clone()

In [73]:
c

tensor([[[1.5414e-43, 1.6115e-43],
         [1.5554e-43, 1.5975e-43],
         [5.6052e-44, 1.2752e-43]]])

In [74]:
id(C)

137455650065376

In [76]:
A.flatten()

tensor([1.5414e-43, 1.6115e-43, 1.5554e-43, 1.5975e-43, 5.6052e-44, 1.2752e-43])