<a href="https://colab.research.google.com/github/sanvi1510/Pytorch/blob/main/Pytorch_lec2_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**AUTOGRAD:**

module to calculate the gradient of any function automatically
(IMPORTANT IN BACK PROPOGATION)

Example 1:
y=x^2

---

Example 2:
y=x**2;
z=sin(y)


In [9]:
import torch
import numpy as np

In [4]:
x=torch.tensor(3.0,requires_grad=True)


Requires_grad:

tell torch that we will be needing this tensors depending on it their gradient gradient and keep the track of all the function on it and torch builds it tree/computation graph


In [18]:
y=x**2

In [19]:
x

tensor(3., requires_grad=True)

In [20]:
y

tensor(9., grad_fn=<PowBackward0>)

In [21]:
z=torch.sin(y)

In [22]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

calculating derivative of y w.r.t x

In [23]:
if x.grad is not None:
    x.grad.zero_()
y.backward(retain_graph=True)
print(x.grad)

tensor(6.)


IMPORTANT

---
1. after the backward function is applied on a tensor in the graph pytorch traverses from the intiall node(X) to the leaf node and find the derivative and the memory for the graph by default is freed for optimization

2.by using retain_graph=true :the memory/graph is retained but the backward can't be applied on same tensor

ABOUT COMPUTATIONAL GRAPHS:

1.  LEAF NODE: INPUT NODE(X)
2.  ROOT NODE:OUTPUT NODE(Y)

THE .grad is only calculated for the leaf node





In [32]:
if x.grad is not None:
    x.grad.zero_() # Clear previous gradients
z.backward(retain_graph=True)
print(x.grad)

tensor(-5.4668)


3.BASIC NUERAL N/W

In [67]:
X=torch.tensor(6.7)
Y=torch.tensor(0.0)

In [68]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(1.0,requires_grad=True)

In [69]:
Y_pred=w*X+b

In [70]:
loss=(Y_pred-Y)**2

In [71]:
loss.backward(retain_graph=True)

In [72]:
b.grad

tensor(15.4000)

In [73]:
w.grad

tensor(103.1800)

In [75]:
w=w-0.01*w.grad
b=b-0.01*b.grad

In [76]:
w


tensor(-1.0636, grad_fn=<SubBackward0>)

In [77]:
b

tensor(0.6920, grad_fn=<SubBackward0>)

IMPORTANT:

---


After the above w and b don't remain leaf nodes as
they are computed using other nodes

In [89]:
m=torch.tensor([1.0,3.0,9.1])

In [90]:
W=torch.tensor([1.0,1.0,1.0],requires_grad=True)
B=torch.tensor([1.0,1.0,1.0],requires_grad=True)

In [91]:
s=m*W+B

In [92]:
s

tensor([ 2.0000,  4.0000, 10.1000], grad_fn=<AddBackward0>)

In [93]:
sum=torch.sum(s)

In [94]:
sum

tensor(16.1000, grad_fn=<SumBackward0>)

In [95]:
scaled_sum = torch.sigmoid(sum)
display(scaled_sum)

tensor(1.0000, grad_fn=<SigmoidBackward0>)

In [96]:
loss=n-scaled_sum

In [97]:
loss.backward(retain_graph=True)

In [101]:
W.grad

tensor([-1.1921e-07, -3.5763e-07, -1.0848e-06])

In [102]:
B.grad

tensor([-1.1921e-07, -1.1921e-07, -1.1921e-07])

CLEARING GRAD:

1.   in normal way the gradient accumate that mean when we do W.grad and B.grad in each backward pass
2.  use x.grad.zero()



STOPING THE BACKWARD PASS AFTER TRAINING:

OPTIONS:


1.   X.require_grad_(False)
2.  Imp: detach():Z=X.detach() (z has the same values as x but not part of the graph and now we will use z instead of x)


1.  imp: no grad(): with torch.no_grad()
  y=x**2




