<a href="https://colab.research.google.com/github/sanvi1510/Pytorch/blob/main/Pytorch_lec_3_simple_nn_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

Processing data

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [19]:
df.shape

(569, 33)

In [20]:
df=df.drop(columns=["Unnamed: 32","id"])
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [22]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
77,18.05,16.15,120.20,1006.0,0.10650,0.21460,0.16840,0.10800,0.2152,0.06673,...,22.39,18.91,150.10,1610.0,0.14780,0.5634,0.37860,0.21020,0.3751,0.11080
250,20.94,23.56,138.90,1364.0,0.10070,0.16060,0.27120,0.13100,0.2205,0.05898,...,25.58,27.00,165.30,2010.0,0.12110,0.3172,0.69910,0.21050,0.3126,0.07849
127,19.00,18.91,123.40,1138.0,0.08217,0.08028,0.09271,0.05627,0.1946,0.05044,...,22.32,25.73,148.20,1538.0,0.10210,0.2264,0.32070,0.12180,0.2841,0.06541
265,20.73,31.12,135.70,1419.0,0.09469,0.11430,0.13670,0.08646,0.1769,0.05674,...,32.49,47.16,214.00,3432.0,0.14010,0.2644,0.34420,0.16590,0.2868,0.08218
149,13.74,17.91,88.12,585.0,0.07944,0.06376,0.02881,0.01329,0.1473,0.05580,...,15.34,22.46,97.19,725.9,0.09711,0.1824,0.15640,0.06019,0.2350,0.07014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,13.62,23.23,87.19,573.2,0.09246,0.06747,0.02974,0.02443,0.1664,0.05801,...,15.35,29.09,97.58,729.8,0.12160,0.1517,0.10490,0.07174,0.2642,0.06953
547,10.26,16.58,65.85,320.8,0.08877,0.08066,0.04358,0.02438,0.1669,0.06714,...,10.83,22.04,71.08,357.4,0.14610,0.2246,0.17830,0.08333,0.2691,0.09479
255,13.96,17.05,91.43,602.4,0.10960,0.12790,0.09789,0.05246,0.1908,0.06130,...,16.39,22.07,108.10,826.0,0.15120,0.3262,0.32090,0.13740,0.3068,0.07957
62,14.25,22.15,96.42,645.7,0.10490,0.20080,0.21350,0.08653,0.1949,0.07292,...,17.67,29.51,119.10,959.5,0.16400,0.6247,0.69220,0.17850,0.2844,0.11320


In [23]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [25]:
X_train

array([[ 1.10116114, -0.77439752,  1.14718662, ...,  1.4252129 ,
         1.34920355,  1.53510109],
       [ 1.92294931,  0.95420774,  1.91761644, ...,  1.42976207,
         0.35255509, -0.31252726],
       [ 1.37129912, -0.13054455,  1.27902488, ...,  0.08472571,
        -0.10191662, -1.06049937],
       ...,
       [-0.06185394, -0.56444546, -0.03812172, ...,  0.32128227,
         0.26006611, -0.2507681 ],
       [ 0.02060923,  0.62528285,  0.16746356, ...,  0.94451783,
        -0.0971327 ,  1.67234368],
       [-0.63340903, -1.05200079, -0.62315399, ..., -1.03952452,
         0.34936581, -0.46063489]])

In [26]:
y_train

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,

In [27]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [28]:
X_train_tensor

tensor([[ 1.1012, -0.7744,  1.1472,  ...,  1.4252,  1.3492,  1.5351],
        [ 1.9229,  0.9542,  1.9176,  ...,  1.4298,  0.3526, -0.3125],
        [ 1.3713, -0.1305,  1.2790,  ...,  0.0847, -0.1019, -1.0605],
        ...,
        [-0.0619, -0.5644, -0.0381,  ...,  0.3213,  0.2601, -0.2508],
        [ 0.0206,  0.6253,  0.1675,  ...,  0.9445, -0.0971,  1.6723],
        [-0.6334, -1.0520, -0.6232,  ..., -1.0395,  0.3494, -0.4606]],
       dtype=torch.float64)

Building Model

In [44]:
class Nueralnetwork():

  def __init__(self,X):

    self.weights=torch.randn(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.sigmoid(torch.matmul(X,self.weights)+self.bias)
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss(self,y_pred,y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [57]:
learning_rate=0.1
epochs=25

In [58]:
model=Nueralnetwork(X_train_tensor)

In [59]:
model.weights

tensor([[-0.0266],
        [-0.8495],
        [ 0.5687],
        [ 0.4242],
        [ 0.3610],
        [-1.9229],
        [ 0.3377],
        [-1.0080],
        [-1.3433],
        [ 0.5320],
        [ 0.5451],
        [-1.4132],
        [ 0.5129],
        [ 0.4758],
        [-3.2782],
        [ 0.4959],
        [-1.3572],
        [ 0.3321],
        [-0.6835],
        [-0.0420],
        [ 0.5986],
        [-0.5885],
        [-0.6307],
        [-0.2217],
        [-1.8220],
        [ 0.4655],
        [-0.0753],
        [ 2.2551],
        [ 2.0665],
        [ 0.2512]], dtype=torch.float64, requires_grad=True)

training pipeline

In [63]:
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)
  #loss calculation
  loss=model.loss(y_pred,y_train_tensor)
  print(epoch,"loss:",loss)
  #backward pass
  loss.backward()
  #updation
   #off.no grad during upadation
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad
    #on grad.zero to stop accumlation
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(epoch," weights:", model.weights)
    print(epoch,"bais:",model.bias)

0 loss: tensor(0.8126, dtype=torch.float64, grad_fn=<NegBackward0>)
0  weights: tensor([[-0.0264],
        [-0.8517],
        [ 0.5690],
        [ 0.4251],
        [ 0.3616],
        [-1.9219],
        [ 0.3374],
        [-1.0076],
        [-1.3413],
        [ 0.5343],
        [ 0.5441],
        [-1.4108],
        [ 0.5121],
        [ 0.4757],
        [-3.2704],
        [ 0.4976],
        [-1.3563],
        [ 0.3328],
        [-0.6802],
        [-0.0377],
        [ 0.5990],
        [-0.5914],
        [-0.6305],
        [-0.2205],
        [-1.8200],
        [ 0.4654],
        [-0.0756],
        [ 2.2558],
        [ 2.0691],
        [ 0.2525]], dtype=torch.float64, requires_grad=True)
0 bais: tensor([-0.0421], dtype=torch.float64, requires_grad=True)
1 loss: tensor(0.8125, dtype=torch.float64, grad_fn=<NegBackward0>)
1  weights: tensor([[-0.0264],
        [-0.8517],
        [ 0.5690],
        [ 0.4252],
        [ 0.3617],
        [-1.9219],
        [ 0.3374],
        [-1.0076],
        [

test

In [62]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  loss=model.loss(y_pred,y_test_tensor)
  print("loss:",loss)

loss: tensor(0.8233, dtype=torch.float64)
